CREATE TABLE BASIC_USER(
	USER_ID VARCHAR(32),
    USER_NAME VARCHAR(100),
    USER_PASSWORD VARCHAR(100)
)

INSERT INTO `CMS`.`BASIC_USER` (`USER_ID`, `USER_NAME`) VALUES ('1', '啊');
INSERT INTO `CMS`.`BASIC_USER` (`USER_ID`, `USER_NAME`) VALUES ('2', 'b');
INSERT INTO `CMS`.`BASIC_USER` (`USER_ID`, `USER_NAME`) VALUES ('3', 'c');
INSERT INTO `CMS`.`BASIC_USER` (`USER_ID`, `USER_NAME`) VALUES ('4', 'd');
INSERT INTO `CMS`.`BASIC_USER` (`USER_ID`, `USER_NAME`) VALUES ('5', 'e');
INSERT INTO `CMS`.`BASIC_USER` (`USER_ID`, `USER_NAME`) VALUES ('6', 'f');
